spring.application.name=TattooMe
#datasource.url=jdbc:mysql://localhost:3306/inzynierkav2
#spring.datasource.username=root
#spring.datasource.password=Cde34rfv
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.sql=trace
logging.level.org.hibernate.orm.jdbc.bind=trace
jwt.secret=ZGlyZWN0ZG96ZW5zZXJpZXNtaWxpdGFyeXNoaXJ0YmFza2V0bHVja3dvbWVucGVvcGxlcGFydGljdWxhcmRvdw==
jwt.expirationMs=3600000

